[04-Oct-2021 19:06:47 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:07:08 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:13:33 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:13:47 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:13:52 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:13:54 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:14:05 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:28:56 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:22 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:22 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:24 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:29 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:29 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:30 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:31 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:31 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:32 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:37 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:37 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:39 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:43 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:43 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:45 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:45 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:45 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:47 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:47 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:47 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 19:51:48 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 20:13:34 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 20:16:39 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 20:20:01 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 20:34:57 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 20:36:10 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 20:36:16 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 20:36:18 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 20:36:57 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:01:12 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:01:14 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:46:23 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:49:32 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:49:32 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:50:55 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:51:03 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:51:05 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:51:25 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:51:27 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:51:28 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:51:36 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:51:46 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:52:03 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:52:10 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:52:29 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:52:46 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:54:02 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:55:42 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:57:48 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:57:53 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 21:57:58 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 22:24:14 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 22:24:17 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 22:45:32 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 22:45:32 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 22:45:35 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 22:45:36 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[04-Oct-2021 23:04:34 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[05-Oct-2021 01:10:50 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[05-Oct-2021 01:57:43 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[05-Oct-2021 01:57:44 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[05-Oct-2021 01:57:47 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[05-Oct-2021 01:57:48 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[05-Oct-2021 07:50:49 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[05-Oct-2021 13:38:51 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[05-Oct-2021 13:39:10 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[05-Oct-2021 14:43:00 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[05-Oct-2021 14:43:02 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[05-Oct-2021 14:43:04 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[HY000] [1045] Access denied for user 'mavsinja_drup1'@'localhost' (using password: YES) in /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 192 #0 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home/sxs4805/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(550): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(903): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(473): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(716): Drupal\Core\DrupalKernel->boot()
#12 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[11-Oct-2021 13:42:04 UTC] Error: Call to a member function save() on null in /home/sxs4805/public_html/core/modules/quickedit/src/QuickEditController.php on line 343 #0 [internal function]: Drupal\quickedit\QuickEditController->entitySave(Object(Drupal\node\Entity\Node))
#1 /home/sxs4805/public_html/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#2 /home/sxs4805/public_html/core/lib/Drupal/Core/Render/Renderer.php(578): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#3 /home/sxs4805/public_html/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#4 /home/sxs4805/public_html/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#5 /home/sxs4805/public_html/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#6 /home/sxs4805/public_html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#7 /home/sxs4805/public_html/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /home/sxs4805/public_html/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /home/sxs4805/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /home/sxs4805/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /home/sxs4805/public_html/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /home/sxs4805/public_html/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /home/sxs4805/public_html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /home/sxs4805/public_html/core/lib/Drupal/Core/DrupalKernel.php(717): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /home/sxs4805/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}
[16-Oct-2021 21:53:55 UTC] Uncaught PHP Exception InvalidArgumentException: "Invalid preceding UUID "631f80b1-e78b-47f1-b7bc-22b942b58b0b"" at /home/sxs4805/public_html/core/modules/layout_builder/src/Section.php line 284
[21-Oct-2021 21:56:39 UTC] Uncaught PHP Exception Drupal\Core\Database\DatabaseExceptionWrapper: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node__field_map_geo.field_map_geo_value' in 'where clause': SELECT COUNT(*) AS "expression"
FROM
(SELECT 1 AS "expression"
FROM
"drup_node" "base_table"
INNER JOIN "drup_node_field_data" "node_field_data" ON "node_field_data"."nid" = "base_table"."nid"
INNER JOIN "drup_node__field_map_geo" "node__field_map_geo" ON "node__field_map_geo"."entity_id" = "base_table"."nid"
WHERE ("node_field_data"."type" = :db_condition_placeholder_0) AND ("node__field_map_geo"."field_map_geo_value" IS NOT NULL)
GROUP BY base_table.vid, base_table.nid) "subquery"; Array
(
    [:db_condition_placeholder_0] => page
)
" at /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/ExceptionHandler.php line 53
[21-Oct-2021 21:56:45 UTC] Uncaught PHP Exception Drupal\Core\Database\DatabaseExceptionWrapper: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node__field_map_geo.field_map_geo_value' in 'where clause': SELECT COUNT(*) AS "expression"
FROM
(SELECT 1 AS "expression"
FROM
"drup_node" "base_table"
INNER JOIN "drup_node_field_data" "node_field_data" ON "node_field_data"."nid" = "base_table"."nid"
INNER JOIN "drup_node__field_map_geo" "node__field_map_geo" ON "node__field_map_geo"."entity_id" = "base_table"."nid"
WHERE ("node_field_data"."type" = :db_condition_placeholder_0) AND ("node__field_map_geo"."field_map_geo_value" IS NOT NULL)
GROUP BY base_table.vid, base_table.nid) "subquery"; Array
(
    [:db_condition_placeholder_0] => page
)
" at /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/ExceptionHandler.php line 53
[21-Oct-2021 21:58:33 UTC] Uncaught PHP Exception Drupal\Core\Database\DatabaseExceptionWrapper: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node__field_map_geo.field_map_geo_value' in 'where clause': SELECT COUNT(*) AS "expression"
FROM
(SELECT 1 AS "expression"
FROM
"drup_node" "base_table"
INNER JOIN "drup_node_field_data" "node_field_data" ON "node_field_data"."nid" = "base_table"."nid"
INNER JOIN "drup_node__field_map_geo" "node__field_map_geo" ON "node__field_map_geo"."entity_id" = "base_table"."nid"
WHERE ("node_field_data"."type" = :db_condition_placeholder_0) AND ("node__field_map_geo"."field_map_geo_value" IS NOT NULL)
GROUP BY base_table.vid, base_table.nid) "subquery"; Array
(
    [:db_condition_placeholder_0] => page
)
" at /home/sxs4805/public_html/core/lib/Drupal/Core/Database/Driver/mysql/ExceptionHandler.php line 53
